name       : ddrescue
version    : '1.23'
release    : 6
source     :
    - https://ftp.gnu.org/gnu/ddrescue/ddrescue-1.23.tar.lz : a9ae2dd44592bf386c9c156a5dacaeeb901573c9867ada3608f887d401338d8d
license    : GPL-2.0
component  : system.utils
summary    : Data recovery tool
description: |
    GNU ddrescue is a data recovery tool. It copies data from one file or block device (hard disc, cdrom, etc) to another, trying to rescue the good parts first in case of read errors.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

