name       : ddrescue
version    : 1.24
release    : 7
source     :
    - https://download.savannah.gnu.org/releases/ddrescue/ddrescue-1.24.tar.lz : 4b5d3feede70e3657ca6b3c7844f23131851cbb6af0cecc9721500f7d7021087
license    : GPL-2.0-or-later
component  : system.utils
summary    : Data recovery tool
description: |
    GNU ddrescue is a data recovery tool. It copies data from one file or block device (hard disc, cdrom, etc) to another, trying to rescue the good parts first in case of read errors.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
