name       : ddrescue
version    : 1.22
release    : 5
source     :
    - https://ftp.gnu.org/gnu/ddrescue/ddrescue-1.22.tar.lz : 09857b2e8074813ac19da5d262890f722e5f7900e521a4c60354cef95eea10a7
license    : GPL-2.0
component  : system.utils
summary    : Data recovery tool
description: |
    GNU ddrescue is a data recovery tool. It copies data from one file or block device (hard disc, cdrom, etc) to another, trying to rescue the good parts first in case of read errors.
builddeps  :
    - lzip
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
