name       : ddrescue
version    : '1.25'
release    : 8
source     :
    - https://download.savannah.gnu.org/releases/ddrescue/ddrescue-1.25.tar.lz : ce538ebd26a09f45da67d3ad3f7431932428231ceec7a2d255f716fa231a1063
license    : GPL-2.0-or-later
component  : system.utils
summary    : Data recovery tool
description: |
    GNU ddrescue is a data recovery tool. It copies data from one file or block device (hard disc, cdrom, etc) to another, trying to rescue the good parts first in case of read errors.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
