name       : ddrescue
version    : 1.19
release    : 1
source     :
    - https://ftp.gnu.org/gnu/ddrescue/ddrescue-1.19.tar.lz : ed8d0c9d9aac80a9110e9cb0d0a91a7390d3bf9f816b67a62ca4eb140f4747b8
license    : GPL-2.0
summary    : Data recovery tool
description: |
    GNU ddrescue is a data recovery tool. It copies data from one file or block device (hard disc, cdrom, etc) to another, trying to rescue the good parts first in case of read errors.
builddeps  :
    - lzip
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
